version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: cinehub-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cinehub
      POSTGRES_USER: cineAdmin
      POSTGRES_PASSWORD: aSdj2127@312311!@jsdaja
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
