version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: my-movies-stats
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mymoviesstats
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: aSdj21Admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
